version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/backend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    groups:
      maven-non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      maven-major:
        patterns:
          - "*"
        update-types:
          - "major"
    ignore:
      - dependency-name: "org.springframework.boot:spring-boot-starter-parent"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    groups:
      angular:
        patterns:
          - "@angular/*"
          - "angular-eslint"
      npm-non-major:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      npm-major:
        patterns:
          - "*"
        update-types:
          - "major"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"
