import { inject, Injectable, signal } from '@angular/core';
import { Auth } from './auth';

const dictionary = {
  'zh-TW': {
    title: '部落格管理',
    login: '登入',
    googleLogin: '使用 Google 登入',
    or: '或',
    accountLinks: '帳號入口',
    needAccount: '註冊新帳號',
    hasAccount: '返回登入',
    forgotPassword: '忘記密碼？',
    verifyEmailHelp: '前往驗證信箱',
    displayNameHint: '顯示名稱需為 1–100 個字元。',
    passwordHint: '請使用不重複的密碼。',
    logout: '登出',
    submit: '送出',
    loading: '載入中…',
    pending: '處理中…',
    loginCallbackProcessing: '正在完成 Google 登入…',
    loginCallbackNoSession: '找不到 Google 登入工作階段，請重新登入。',
    loginCallbackError: 'Google 登入未完成，請再試一次。',
    empty: '目前沒有資料',
    forbidden: '您沒有權限',
    notFound: '找不到頁面',
    error: '目前無法完成操作',
    success: '已完成',
    nav: {
      publicArticles: '公開文章',
      articles: '文章管理',
      invitations: '邀請管理',
      password: '密碼設定',
      users: '使用者',
      profile: '個人資料',
      sessions: '登入工作階段',
      tags: '標籤',
      deletedArticles: '已刪除文章',
      email: '電子信箱',
    },
    authTitles: {
      register: '註冊',
      verifyEmail: '驗證電子信箱',
      verifyResend: '重新寄送驗證信',
      passwordReset: '申請重設密碼',
      resetPassword: '重設密碼',
      confirmEmail: '確認電子信箱',
      invite: '接受邀請',
    },
    history: {
      operatorId: '操作者',
      previousValue: '先前數值',
      newValue: '新數值',
      changedAt: '變更時間',
    },
    field: {
      email: '電子信箱',
      password: '密碼',
      displayName: '顯示名稱',
      preferredLanguage: '偏好語言',
      token: '驗證碼',
      currentPassword: '目前密碼',
      newPassword: '新密碼',
      title: '標題',
      content: '內容',
      status: '狀態',
      tagNames: '標籤',
      version: '版本',
      value: '最小密碼長度',
      role: '角色',
      enabled: '啟用',
      minimumLength: '最小密碼長度',
    },
    languages: { zhTW: '繁體中文（台灣）', en: 'English' },
    search: '搜尋標題',
    searchAction: '搜尋',
    invitationsHeading: '邀請',
    invitationHint: '輸入成員電子信箱，系統將發送註冊邀請信',
    historyHeading: '密碼長度變更歷程',
    userInfo: '使用者資訊',
    data: '資料',
    required: '必填',
    draft: '草稿',
    draftCode: '草稿',
    published: '已發布',
    publishedCode: '已發布',
    newArticle: '新增文章',
    revoke: '撤銷',
    sessionCurrent: '目前工作階段',
    sessionCreatedAt: '建立時間',
    sessionLastUsedAt: '最後使用時間',
    delete: '刪除',
    restore: '還原',
    role: '角色',
    enabled: '啟用',
    disabled: '停用',
    update: '更新',
    toggle: '切換啟用狀態',
    previous: '上一頁',
    next: '下一頁',
    page: '第',
    of: '頁，共',
    pageSuffix: '頁',
    remove: '移除',
    filterArticles: '篩選文章',
    clearFilter: '清除篩選',
    authorAttribution: '作者署名',
    actions: '操作',
    edit: '編輯',
    conflict: '409 — 資料衝突',
    unauthorized: '401 — 請重新登入',
    confirmDelete: '刪除文章「{title}」？',
    confirmDisable: '確定要停用 {name}？',
    enableAction: '啟用帳號',
    disableAction: '停用帳號',
    invalidToken: '此連結無效或已過期，請重新索取連結。',
    retryAction: '重新載入',
    invitationValidating: '正在確認邀請連結…',
    invitationEmail: '受邀電子信箱',
    invitationExpired: '此邀請已過期，請向管理員索取新的邀請。',
    invitationAlreadyUsed: '此邀請已使用，請直接登入。',
    invitationInvalid: '此邀請連結無效，請向管理員索取新的邀請。',
    invitationRequestError: '目前無法確認邀請連結，請再試一次。',
    invitationAccepted: '邀請已接受，請登入以繼續。',
    deleteSuccess: '已刪除文章「{title}」',
    viewDeleted: '查看已刪除文章',
    deletedNotice: '已刪除的文章將在 30 天後永久移除',
    permanentDelete: '永久刪除',
    confirmPermanentDelete: '確定要永久刪除文章「{title}」？此操作無法復原。',
    permanentDeleteSuccess: '已永久刪除文章「{title}」',
    cancel: '取消',
    currentValue: '目前數值',
    passwordRule: '數值必須介於 8 至 128',
    availableTags: '現有標籤',
    customTags: '自訂新標籤',
    customTagsHint: '以逗號分隔多個標籤',
    titlePlaceholder: '請輸入文章標題…',
    contentPlaceholder: '在此撰寫文章內容…',
    tagNamesPlaceholder: '例如：tech, tutorial, release',
    roles: { AUTHOR: '作者', ADMIN: '管理員' },
    statuses: { DRAFT: '草稿', PUBLISHED: '已發布' },
  },
  en: {
    title: 'Blog Admin',
    login: 'Sign in',
    googleLogin: 'Continue with Google',
    or: 'or',
    accountLinks: 'Account access',
    needAccount: 'Create an account',
    hasAccount: 'Back to sign in',
    forgotPassword: 'Forgot password?',
    verifyEmailHelp: 'Verify email',
    displayNameHint: 'Display name must be 1–100 characters.',
    passwordHint: 'Use a unique password.',
    logout: 'Sign out',
    submit: 'Submit',
    loading: 'Loading…',
    pending: 'Pending…',
    loginCallbackProcessing: 'Finishing Google sign-in…',
    loginCallbackNoSession: 'No Google sign-in session was found. Please sign in again.',
    loginCallbackError: 'Google sign-in was not completed. Please try again.',
    empty: 'Nothing here yet',
    forbidden: 'You do not have permission',
    notFound: 'Page not found',
    error: 'Something went wrong',
    success: 'Done',
    nav: {
      publicArticles: 'Articles',
      articles: 'Manage articles',
      invitations: 'Invitations',
      password: 'Password settings',
      users: 'Users',
      profile: 'Profile',
      sessions: 'Sessions',
      tags: 'Tags',
      deletedArticles: 'Deleted articles',
      email: 'Email',
    },
    authTitles: {
      register: 'Register',
      verifyEmail: 'Verify email',
      verifyResend: 'Resend verification',
      passwordReset: 'Password reset',
      resetPassword: 'Reset password',
      confirmEmail: 'Confirm email',
      invite: 'Accept invitation',
    },
    history: {
      operatorId: 'Operator',
      previousValue: 'Previous value',
      newValue: 'New value',
      changedAt: 'Changed at',
    },
    field: {
      email: 'Email',
      password: 'Password',
      displayName: 'Display name',
      preferredLanguage: 'Preferred language',
      token: 'Token',
      currentPassword: 'Current password',
      newPassword: 'New password',
      title: 'Title',
      content: 'Content',
      status: 'Status',
      tagNames: 'Tags',
      version: 'Version',
      value: 'Minimum password length',
      role: 'Role',
      enabled: 'Enabled',
      minimumLength: 'Minimum password length',
    },
    languages: { zhTW: '繁體中文（台灣）', en: 'English' },
    search: 'Search title',
    searchAction: 'Search',
    invitationsHeading: 'Invitations',
    invitationHint: 'Enter email to send an invitation link',
    historyHeading: 'Password Policy History',
    userInfo: 'User',
    data: 'Data',
    required: 'Required',
    draft: 'Draft',
    draftCode: 'DRAFT',
    published: 'Published',
    publishedCode: 'PUBLISHED',
    newArticle: 'New article',
    revoke: 'Revoke',
    sessionCurrent: 'Current session',
    sessionCreatedAt: 'Created at',
    sessionLastUsedAt: 'Last used at',
    delete: 'Delete',
    restore: 'Restore',
    role: 'Role',
    enabled: 'Enabled',
    disabled: 'Disabled',
    update: 'Update',
    toggle: 'Toggle enabled',
    previous: 'Previous',
    next: 'Next',
    page: 'Page',
    of: 'of',
    pageSuffix: '',
    remove: 'Remove',
    filterArticles: 'Filter articles',
    clearFilter: 'Clear filter',
    authorAttribution: 'Author Attribution',
    actions: 'Actions',
    edit: 'Edit',
    conflict: '409 — Data conflict',
    unauthorized: '401 — Please sign in again',
    confirmDelete: 'Delete article "{title}"?',
    confirmDisable: 'Disable {name}?',
    enableAction: 'Enable account',
    disableAction: 'Disable account',
    invalidToken: 'This link is invalid or expired. Please request a new one.',
    retryAction: 'Reload',
    invitationValidating: 'Checking invitation link…',
    invitationEmail: 'Invited email',
    invitationExpired: 'This invitation has expired. Ask an administrator for a new invitation.',
    invitationAlreadyUsed: 'This invitation has already been used. Please sign in.',
    invitationInvalid:
      'This invitation link is invalid. Ask an administrator for a new invitation.',
    invitationRequestError: 'We could not check this invitation link. Please try again.',
    invitationAccepted: 'Invitation accepted. Please sign in to continue.',
    deleteSuccess: 'Article "{title}" deleted',
    viewDeleted: 'View deleted articles',
    deletedNotice: 'Deleted articles are permanently removed after 30 days',
    permanentDelete: 'Delete permanently',
    confirmPermanentDelete: 'Permanently delete article "{title}"? This cannot be undone.',
    permanentDeleteSuccess: 'Article "{title}" permanently deleted',
    cancel: 'Cancel',
    currentValue: 'Current value',
    passwordRule: 'Value must be between 8 and 128',
    availableTags: 'Existing tags',
    customTags: 'Custom tags',
    customTagsHint: 'Separate multiple tags with commas',
    titlePlaceholder: 'Enter article title…',
    contentPlaceholder: 'Write article content here…',
    tagNamesPlaceholder: 'e.g. tech, tutorial, release',
    roles: { AUTHOR: 'Author', ADMIN: 'Administrator' },
    statuses: { DRAFT: 'Draft', PUBLISHED: 'Published' },
  },
} as const;

@Injectable({ providedIn: 'root' })
export class Language {
  private readonly auth = inject(Auth);

  readonly lang = signal<'zh-TW' | 'en'>(this.initial());
  readonly error = signal('');

  get t() {
    return dictionary[this.lang()];
  }

  set(lang: 'zh-TW' | 'en') {
    this.error.set('');
    this.lang.set(lang);
    localStorage.setItem('blog-admin-language', lang);

    if (this.auth.user) {
      this.auth.saveLanguage(lang).subscribe({ error: () => this.error.set(this.t.error) });
    }
  }

  usePreferred(lang: 'zh-TW' | 'en') {
    this.lang.set(lang);
    localStorage.setItem('blog-admin-language', lang);
  }

  private initial(): 'zh-TW' | 'en' {
    const value = localStorage.getItem('blog-admin-language');

    if (value === 'en' || value === 'zh-TW') {
      return value;
    }

    return navigator.language.toLowerCase().startsWith('en') ? 'en' : 'zh-TW';
  }
}
